SELECT TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
 /* TABLE_SCHEMA = "${1:db_name}" AND (TABLE_NAME = "${2:table_name}" OR REFERENCED_TABLE_NAME="${2:table_name}") AND */
 REFERENCED_COLUMN_NAME is not NULL;